source 'http://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
gem 'mysql2'

gem 'json'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

#platforms :ruby do
	# Use unicorn as the app server
	#gem 'unicorn-rails'
	#gem 'puma'
#end

# For windows because unicorn doesn't work on it
gem 'specific_install', platforms: [:x64_mingw,:mingw, :mswin]
gem 'thin'#, platforms: [:x64_mingw,:mingw, :mswin]
gem 'eventmachine', :git => 'https://github.com/eventmachine/eventmachine.git', platforms: [:x64_mingw,:mingw, :mswin]

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

# Asset gems
# Use Haml for page structure
gem 'haml', '~> 4.0.5'
gem "haml-rails"
# Use SCSS for stylesheets
gem 'sass-rails'#, '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
# gem 'coffee-rails', '~> 4.0.0'
# Use jquery and angularjs as the JavaScript library
gem 'jquery-rails', "~> 2.3.0"
gem 'jquery-ui-rails', '~> 5.0.5'
gem 'angularjs-rails'
gem 'angular-csrf-cookie-rails'
gem 'tilt'
# Provide Foundation for the rails app
gem 'foundation-rails'
# Icons from foundation
gem 'foundation-icons-sass-rails'

platforms :ruby do #We doesn't dev' on Windows so we avoid errors thanks to this
	# Debug gems
	#For debug
	gem 'annotate'
	gem 'better_errors'
	#better print
	gem 'priscilla'
	gem "binding_of_caller"
end

# For test
gem 'simplecov', :require => false, :group => :test

#needed by activeadmin
gem "devise"
gem 'kaminari'

#Features
gem "gritter"
gem 'activeadmin', github: 'activeadmin'
#gem 'meta_search'

#gem sprocket
gem "sprockets", "~> 2.12.3"
gem "sprockets-rails", "~> 2.2.4"

gem "paperclip", "~> 4.1"
#gem "will_paginate"

#gem to have a better design for rdoc. To launch like this : rdoc --format=fivefish
gem 'rdoc-generator-fivefish'


# For Windows with ruby 2.0 and Rails 4.1
gem 'tzinfo-data', platforms: [:x64_mingw,:mingw, :mswin]

require 'rbconfig'
gem 'wdm', '>= 0.1.0' if RbConfig::CONFIG['target_os'] =~ /mswin|mingw|cygwin/i

# OAuth gems
gem 'omniauth'
gem 'omniauth-oauth2', '~> 1.1'
gem 'omniauth-twitter'
gem 'omniauth-facebook', '~> 2.0.0.pre1'
gem 'omniauth-google-oauth2', '~> 0.2.6'

# Websocket support
gem 'websocket-rails', platforms: :ruby

# For playlist
gem 'ranked-model'